sudo: false
language: go

go:
  - 1.5

before_script:
  - go get github.com/golang/lint/golint

script:
  - go build ./...
  - golint ./...
  - go test -short -v ./...

after_script:
  - F=$(go fmt ./...); if [ ! -z "$F" ]; then echo "Please gofmt for"$'\n'"$F"; exit 1; fi
